name: Container Image for Reducer

on:
  push:
    branches:
      - main
    tags:
      - "v*"
      - "*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: reducer

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Determine tags
        id: determine_tags
        shell: bash
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tags=${{ github.ref_name }} latest" >> $GITHUB_OUTPUT
          else
            echo "tags=latest" >> $GITHUB_OUTPUT
          fi

      - name: Buildah Action
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.determine_tags.outputs.tags }}
          oci: true
          containerfiles: containerfile
          context: .

      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
